version: "3"

volumes:
  pgdatasource:

services:
  blogapp-db:
    image: postgres
    restart: always
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: blog_db
      POSTGRES_HOST: postgresql
    env_file:
      - api/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdatasource:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      blogapp-db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=blogapp-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
      - POSTGRES_DB=blog_db
    volumes:
      - type: bind
        source: ./api
        target: /app
    command: npm run start:dev

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./ui
        target: /app
    depends_on:
      - "api"
